version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: all
  disable:
    - depguard
    - dupl
    - errorlint
    - exhaustruct
    - funlen
    - gocognit
    - godox
    - mnd
    - noctx
    - nosprintfhostport
    - testpackage
  settings:
    tagalign:
      sort: false
    varnamelen:
      ignore-names:
        - id
        - i
      ignore-type-assert-ok: true
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
        - wg *sync.WaitGroup
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
          - lll
        path: _test\.go
      - linters:
          - lll
        source: '`.*`'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
