run:
  # Allowed values: readonly|vendor|mod
  # By default, it isn't set.
  modules-download-mode: readonly

output:
  formats: 
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    #- asasalint
    #- asciicheck
    #- bidichk
    #- bodyclose
    #- canonicalheader
    #- containedctx
    - contextcheck
    #- copyloopvar
    - cyclop
    #- decorder
    - depguard
    #- dogsled
    #- dupl
    #- dupword
    #- durationcheck
    - err113
    #- errcheck
    #- errchkjson
    #- errname
    - errorlint
    - execinquery # Deprecated
    #- exhaustive
    - exhaustruct
    - exportloopref # Deprecated
    #- fatcontext
    #- forbidigo
    #- forcetypeassert
    - funlen
    - gci
    #- ginkgolinter
    #- gocheckcompilerdirectives
    - gochecknoglobals
    #- gochecknoinits
    #- gochecksumtype
    - gocognit
    #- goconst
    #- gocritic
    #- gocyclo
    - godot
    - godox
    #- gofmt
    #- gofumpt
    #- goheader
    #- goimports
    - gomnd # Deprecated
    #- gomoddirectives
    #- gomodguard
    #- goprintffuncname
    #- gosec
    - gosimple
    #- gosmopolitan
    - govet
    #- grouper
    #- importas
    #- inamedparam
    #- ineffassign
    #- interfacebloat
    - intrange
    #- ireturn
    - lll
    #- loggercheck
    #- maintidx
    #- makezero
    #- mirror
    #- misspell
    - mnd
    - musttag
    #- nakedret
    - nestif
    #- nilerr
    #- nilnil
    - nlreturn
    - noctx
    #- nolintlint
    #- nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    #- prealloc
    #- predeclared
    #- promlinter
    #- protogetter
    #- reassign
    - revive
    #- rowserrcheck
    #- sloglint
    #- spancheck
    #- sqlclosecheck
    #- staticcheck
    - stylecheck
    - tagalign
    #- tagliatelle
    #- tenv
    #- testableexamples
    - testifylint
    - testpackage
    #- thelper
    #- tparallel
    #- unconvert
    #- unparam
    - unused
    - usestdlibvars
    - varnamelen
    #- wastedassign
    #- whitespace
    - wrapcheck
    - wsl
    #- zerologlint
