run:
  # Allowed values: readonly|vendor|mod
  # By default, it isn't set.
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  varnamelen:
    ignore-type-assert-ok: true
    ignore-decls:
      - "w http.ResponseWriter"
      - "r *http.Request"
      - "wg *sync.WaitGroup"
    ignore-names:
      - id
      - i # Iterator
  tagalign:
    sort: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - gochecknoglobals
    - source: "`.*`"
      linters:
      - lll # Because of the struct tags

linters:
  enable-all: true
  disable:
    - depguard
    - dupl
    - errorlint
    - exhaustruct
    - exportloopref # Deprecated
    - funlen
    - gocognit
    - godox
    - mnd
    - noctx
    - nosprintfhostport
    - testpackage
