version: "3"

networks:
  monitoring:
    external: true
    name: monitoring
  web:
    external: true
    name: web

services:
  # Postgres
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    networks:
      - monitoring
    volumes:
      - /data/postgres_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    user: 1000:1000 # only uncomment after the database is created, with the correct uid:gid
    restart: always

  # Fetcher
  livetrack-fetcher:
    image: fahy.xyz/livetrack:v1.1.0
    environment:
      - PORT=9101
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - METRICS_SUBSYSTEM=fetcher
    command: /livetrack fetcher
    ports:
      - 9101:9101
    networks:
      - monitoring
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=9101"
    restart: unless-stopped

  # Backend
  livetrack-backend:
    image: fahy.xyz/livetrack:v1.1.0
    environment:
      - PORT=8081
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - METRICS_SUBSYSTEM=backend
    command: /livetrack web
    expose:
      - 8081
    ports:
      - 8081:8081
    networks:
      - monitoring
      - web
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=8081"
      - "traefik.enable=true"
      # Backend is accessible at /api/
      - "traefik.http.routers.livetrack-backend.rule=Host(`livetrack.fahy.xyz`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.livetrack-backend.tls=true"
      - "traefik.http.routers.livetrack-backend.entrypoints=websecure"
      # HTTPS certificate resolver
      - "traefik.http.routers.livetrack-backend.tls.certresolver=resolverlivetrackfahy"
    restart: unless-stopped

  # Frontend
  livetrack-frontend:
    image: fahy.xyz/livetrack-web:v0.0.1-rc7
    environment:
      - PUBLIC_MAPTILE_API_KEY={$MAPTILE_API_KEY}
      - PUBLIC_BACKEND_ENDPOINT={$BACKEND_ENDPOINT}
    networks:
      - monitoring
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.livetrack-frontend.rule=Host(`livetrack.fahy.xyz`)"
      - "traefik.http.routers.livetrack-frontend.tls=true"
      # HTTPS certificate resolver
      - "traefik.http.routers.livetrack-frontend.tls.certresolver=resolverlivetrackfahy"
    restart: unless-stopped

  # Livetrack test
  #livetrack-test:
  #  image: fahy.xyz/livetrack:v1.1.0
  #  environment:
  #    - PORT=9102
  #    - POSTGRES_HOST=postgres
  #    - POSTGRES_USER=${POSTGRES_USER}
  #    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #    - ORGANIZATION=alpsfreeride
  #    - TELEGRAM_CHANNEL=@test_tracking_go
  #    - TELEGRAM_TOKEN=${TELEGRAM_TOKEN_TEST_TRACKING_GO}
  #    - METRICS_SUBSYSTEM=bot
  #  command: /livetrack bot
  #  ports:
  #    - 9102:9102
  #  networks:
  #    - monitoring
  #  labels:
  #    - "prometheus.io/scrape=true"
  #    - "prometheus.io/port=9102"
  #    - "prometheus.io/extra-labels=livetrack:@test_tracking_go"
  #  restart: unless-stopped

  # Alpsfreeride
  livetrack-alpsfreeride:
    image: fahy.xyz/livetrack:v1.1.0
    environment:
      - PORT=9103
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ORGANIZATION=alpsfreeride
      - TELEGRAM_CHANNEL=@alpsfreeride_tracking
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - METRICS_SUBSYSTEM=bot
    command: /livetrack bot
    ports:
      - 9103:9103
    networks:
      - monitoring
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=9103"
      - "prometheus.io/extra-labels=livetrack:@alpsfreeride"
    restart: unless-stopped

  # Axlair
  livetrack-axlair:
    image: fahy.xyz/livetrack:v1.1.0
    environment:
      - PORT=9104
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ORGANIZATION=axlair
      - TELEGRAM_CHANNEL=@axlair_tracking
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - METRICS_SUBSYSTEM=bot
    command: /livetrack bot
    ports:
      - 9104:9104
    networks:
      - monitoring
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=9104"
      - "prometheus.io/extra-labels=livetrack:@axlair"
    restart: unless-stopped

  # Followus
  livetrack-followus:
    image: fahy.xyz/livetrack:v1.1.0
    environment:
      - PORT=9105
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ORGANIZATION=followus
      - TELEGRAM_CHANNEL=@FollowUsIfYouCan_channel
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - METRICS_SUBSYSTEM=bot
    command: /livetrack bot
    ports:
      - 9105:9105
    networks:
      - monitoring
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=9105"
      - "prometheus.io/extra-labels=livetrack:@followus"
    restart: unless-stopped

